# How add a custom shop:
# First create a new .csv file in the folder shops
# Second add the file name to this section
shops: [ "food" ]

# Format to add prices:
# Material,BuyPrice,SellPrice
# If you set any price in 0, you can't buy or sell the item
# Please see materials in docs.
# 1.8.8: https://helpch.at/docs/1.8/org/bukkit/Material.html

# Enable ShopEvent
enable-event: false

# Enable ShopApi
enable-api: false

principal-inventory:
  rows: 3
  title: "&0&lShopGui &0| Click on item"

sellOrBuy-inventory:
  rows: 5
  title: "&0Sell or buy" 

shop-inventory:
  rows: 5
  title: "&0Select a item"

# To set custom head use:
# HEAD:base64

buy-buttons:
  amounts: [ 1, 8, 16, 32, 64 ]
  material: "HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTNlOWY0ZGJhZGRlMGY3MjdjNTgwM2Q3NWQ4YmIzNzhmYjlmY2I0YjYwZDMzYmVjMTkwOTJhM2EyZTdiMDdhOSJ9fX0="
  name: "&aClick here to buy"
  1:
    slot: 29
  8:
    slot: 30
  16:
    slot: 31
  32:
    slot: 32
  64:
    slot: 33

sell-buttons:
  amounts: [ 1, 8, 16, 32, 64 ]
  material: "HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTQ4ZDdkMWUwM2UxYWYxNDViMDEyNWFiODQxMjg1NjcyYjQyMTI2NWRhMmFiOTE1MDE1ZjkwNTg0MzhiYTJkOCJ9fX0="
  name: "&cClick here to sell"
  1:
    slot: 20
  8:
    slot: 21
  16:
    slot: 22
  32:
    slot: 23
  64:
    slot: 24

# Max items per page
items-end-slot: 27

item-lore:
  - "&fBuy price: &a{0}"
  - "&fSell price: &c{1}"

next-page:
  name: "&aNext page"
  material: "HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGJmOGI2Mjc3Y2QzNjI2NjI4M2NiNWE5ZTY5NDM5NTNjNzgzZTZmZjdkNmEyZDU5ZDE1YWQwNjk3ZTkxZDQzYyJ9fX0="
  slot: 45

previous-page:
  name: "&cBack"
  material: "HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjc2MjMwYTBhYzUyYWYxMWU0YmM4NDAwOWM2ODkwYTQwMjk0NzJmMzk0N2I0ZjQ2NWI1YjU3MjI4ODFhYWNjNyJ9fX0="
  slot: 37

food:
  # Inventory
  title: "&0&lFood section"

  # Principal Inventory item
  slot: 13
  material: "HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNThiYWQyYzJkNDgzNzQxYWUwYTdiNGE0YmY0MzQyMTI3MGIwZTVkZWI0NjRkNGY4NWZkNzY4OGIxYTYwYjRlOSJ9fX0="
  name: "&6&lFood"
  lore: # Remove this section for don't set lore
    - "&7 See delicious food"